name       : gnome-sushi
version    : 3.32.0
release    : 7
source     :
    - https://download.gnome.org/sources/sushi/3.32/sushi-3.32.0.tar.xz : dd622e169874778876b0c2406f6529de6022f3e3f63890602207bf342e463138
license    : GPL-2.0
component  : desktop.gnome
summary    : Sushi is a quick previewer for Nautilus.
description: |
    Sushi is a quick previewer for Nautilus.
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(evince-document-3.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
