name       : gnome-sushi
version    : '42.0'
release    : 16
source     :
    - https://download.gnome.org/sources/sushi/42/sushi-42.0.tar.xz : 45d8db7af45a79784e7a34588d149ea955c8be44bb82a36e896829405b7c8820
homepage   : https://gitlab.gnome.org/GNOME/sushi
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Sushi is a quick previewer for Nautilus
description: |
    Sushi is a quick previewer for Nautilus.
builddeps  :
    - pkgconfig(evince-document-3.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-4.0)
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
