name       : gnome-sushi
version    : 3.24.0
release    : 4
source     :
    - https://download.gnome.org/sources/sushi/3.24/sushi-3.24.0.tar.xz : f90bb95172664486f8d529995007fd12f0df9d0c998e20658b6203f46ce70d48
license    : GPL-2.0
component  : desktop.gnome
summary    : Sushi is a quick previewer for Nautilus.
description: |
    Sushi is a quick previewer for Nautilus.
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(evince-document-3.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
