name       : gnome-sushi
version    : '44.2'
release    : 18
source     :
    - https://download.gnome.org/sources/sushi/44/sushi-44.2.tar.xz : 6c002fe0aea19027ba448b5aec94d5cd753c9752f996ee033152428738ea43e9
homepage   : https://gitlab.gnome.org/GNOME/sushi
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Sushi is a quick previewer for Nautilus
description: |
    Sushi is a quick previewer for Nautilus.
builddeps  :
    - pkgconfig(evince-document-3.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-4.1)
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
