name       : gnome-sushi
version    : '41.2'
release    : 15
source     :
    - https://download.gnome.org/sources/sushi/41/sushi-41.2.tar.xz : b59fb42c9965c7361f76296dd2a34045ab655065ea4143de5ac8b2ca0caaea5e
homepage   : https://gitlab.gnome.org/GNOME/sushi
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Sushi is a quick previewer for Nautilus
description: |
    Sushi is a quick previewer for Nautilus.
builddeps  :
    - pkgconfig(evince-document-3.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-4.0)
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
