name       : gnome-sushi
version    : 3.20.0
release    : 1
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/sushi/3.20/sushi-3.20.0.tar.xz : 6e729c789e9e7f02505e25d4ac6cfed47e676366f0942fca740094f7fe9eae9e
license    : GPL-2.0
component  : desktop.gnome
summary    : Sushi is a quick previewer for Nautilus.
description: |
    Sushi is a quick previewer for Nautilus.
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(evince-document-3.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
