name       : gnome-sushi
version    : 3.38.0
release    : 11
source     :
    - https://download.gnome.org/sources/sushi/3.38/sushi-3.38.0.tar.xz : 5040029f7ffb6fd5491ca2db94202cca2450c3a56afba515d9d53713d2c4986e
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Sushi is a quick previewer for Nautilus.
description: |
    Sushi is a quick previewer for Nautilus.
builddeps  :
    - pkgconfig(evince-document-3.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
